name: Build CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [published]

env:
  GO111MODULE: on

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.7
        # Whether to download only stable versions
        stable: true

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true

    - name: Build
      run: make

    - name: Publish
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
