name: Build CI

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

env:
  GO111MODULE: on

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: webapp/package.json

    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true

    - name: Build
      run: make

    - name: Publish
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
